startups <- read.csv(file.choose())
View(startups)
summary(startups)
colnames(startups) <- c("researchanddevelopment","administration","marketing","state","profit")
View(startups)
plot(startups)
plot(researchanddevelopment,profit)
attach(startups)
pairs(startups)
cor(startups[,-4])
library(corpcor)
cor2pcor(cor(startups[,-4]))
attach(startups)
input <- lm(researchanddevelopment~administration+marketing+state+profit,data = startups)
inputA <- lm(researchanddevelopment~administration)
summary(inputA)
summary(input)
plot(input)
library(car)
influence.measures(input)
influenceIndexPlot(input)
influencePlot(input)
input1 <- lm(researchanddevelopment~administration+marketing+state+profit,data = startups[,-50])
summary(input1)
vif(input)
input.final <- lm(researchanddevelopment~administration+marketing+state,data = startups[,-50])
summary(input.final)
plot(input.final)
library(MASS)
stepAIC(input)
avPlots(input,id.n=5,id.cex=100, col="red")
