emp_data <- read.csv(file.choose())
View(emp_data)
summary(emp_data)
library(lattice)
dotplot(emp_data$Salary_hike,main="Dot Plot of Salary Hike")
dotplot(emp_data$Churn_out_rate,main="Dot Plot of Churn_out_rate")
plot(emp_data)
attach(emp_data)
cor(Salary_hike,Churn_out_rate)
reg <- lm(Churn_out_rate~Salary_hike,data = emp_data)
summary(reg)
confint(reg,level=0.95)
pred <- predict(reg,interval="predict")
reg_sqrt <- lm(Churn_out_rate~sqrt(Salary_hike),data = emp_data)
summary(reg_sqrt)
pred1 <- predict(reg_sqrt,interval="predict")
pred1 <- as.data.frame(pred1)
reg_log <- lm(Salary_hike~log(Churn_out_rate), data = emp_data)
summary(reg_log)
reg1 <- lm(log(Churn_out_rate)~Salary_hike+I(Salary_hike*Salary_hike),data = emp_data)
summary(reg1)
reg2 <- predict(reg1)
reg3<- exp(reg2)
library(ggplot2)
ggplot(data = emp_data, aes(x = Salary_hike + I(Salary_hike^2) + I(Salary_hike^3), y = Churn_out_rate)) + 
  geom_point(color='blue') +
  geom_line(color='red',data = emp_data, aes(x=Salary_hike+I(Salary_hike^2)+I(Salary_hike^3), y=reg2))
