Salary_data <- read.csv(file.choose())
View(Salary_data)
summary(Salary_data)
library(lattice)
dotplot(Salary_data$Salary,main="Dot Plot of salary")
dotplot(Salary_data$YearsExperience, main="Dot Plot of YearsExperience")
plot(Salary_data)
attach(Salary_data)
cor(Salary,YearsExperience)
reg <- lm(Salary~YearsExperience,data = Salary_data)
summary(reg)
confint(reg,level=0.95)
pred <- predict(reg,interval="predict")
reg_sqrt <- lm(Salary~sqrt(YearsExperience), data = Salary_data)
summary(reg_sqrt)
pred1 <- predict(reg_sqrt, interval="predict")
pred1 <- as.data.frame(pred1)
reg_log <- lm(Salary~log(YearsExperience), data = Salary_data)
summary(reg_log)
reg1 <- lm(log(Salary)~YearsExperience+I(YearsExperience*YearsExperience),data = Salary_data)
summary(reg1)
reg2 <- predict(reg1)
reg3 <- exp(reg2)
library(ggplot2)
ggplot(data = Salary_data, aes(x = YearsExperience + I(YearsExperience^2) + I(YearsExperience^3), y = Salary)) + 
  geom_point(color='blue') +
  geom_line(color='red',data = Salary_data, aes(x=YearsExperience+I(YearsExperience^2)+I(YearsExperience^3), y=reg3))
