calories_consumed <- read.csv(file.choose())
View(calories_consumed)
summary(calories_consumed)
plot(calories_consumed)
plot(calories_consumed$Weight.gained..grams.,calories_consumed$Calories.Consumed)
attach(calories_consumed)
library(lattice)
dotplot(calories_consumed$Weight.gained..grams.,main="Dot Plot of Weight.gained..grams")
dotplot(calories_consumed$Calories.Consumed,main="Dot Plot of Calories.Consumed")
cor(Calories.Consumed,Weight.gained..grams.)
reg <- lm(Calories.Consumed~Weight.gained..grams.,data = calories_consumed)
summary(reg)
confint(reg,level = 0.95)
pred <- predict(reg,interval="predict")
reg_sqrt <- lm(Weight.gained..grams.~sqrt(Calories.Consumed),data = calories_consumed)
summary(reg_sqrt)
pred1 <- predict(reg_sqrt,interval="predict")
pred1 <- as.data.frame(pred1)
reg_log <- lm(Weight.gained..grams.~log(Calories.Consumed),data = calories_consumed)
summary(reg_log)
reg1 <- lm(log(Weight.gained..grams.)~Calories.Consumed+I(Calories.Consumed*Calories.Consumed),data = calories_consumed)
summary(reg1)
reg2 <- predict(reg1)
reg3 <- exp(reg2)
library(ggplot2)
ggplot(data = calories_consumed, aes(x = Calories.Consumed + I(Calories.Consumed^2) + I(Calories.Consumed^3), y = Weight.gained..grams.)) + 
  geom_point(color='blue') +
  geom_line(color='red',data = calories_consumed, aes(x=Calories.Consumed+I(Calories.Consumed^2)+I(Calories.Consumed^3), y=reg3))

